openapi: 3.0.1
info:
  title: '@jupiterone/graph-circleci'
  description: A JupiterOne Integration for ingesting data of the CircleCI
  x-cortex-git:
    github:
      repository: JupiterOne/graph-circleci
  x-cortex-owners:
    - type: group
      name: JupiterOne/integrations
  x-cortex-tag: '@jupiterone/graph-circleci'
  x-cortex-service-groups:
    - tier-4
